###

POST http://localhost:3001/user/signup
Content-Type: application/json

{
  "Full_name": "Amanda Chepkoech",
  "Email": "amanda@example.com",
  "Password": "password1234"
}


###

POST http://localhost:3001/user/login
Content-Type: application/json

{
  "Email": "amanda@example.com",
  "Password": "password1234"
}

###

POST  http://localhost:3001/projects/create
Content-Type: application/json

{
          "ProjectName": " Biking",
          "ProjectDescription": " Go for a ride",
          "AssignedTo": "Cherotich Sharon",
          "AssigneeName": "Cherotich Sharon",
          "EndDate": "14/02/2024" 
}
###

GET http://localhost:3001/projects/allprojects

###

GET  http://localhost:3001/users/allusers


###

DELETE http://localhost:3001/projects/delete/A7048D47-57D3-4562-B3F0-714152710511
Content-Type: application/json

